// packages/vue-app/src/cart/cart-content.vue
<template>
    <div id="info-container" v-if="state.kind === 'LoadingCartState'">
        <ProgressSpinner />
    </div>
    <div id="info-container" v-if="state.kind === 'ErrorCartState'">Error</div>
    <div id="items-container" v-if="state.kind === 'UpdatedCartState'">
        <div v-if="state.items.length > 0" style="max-height: 650px; overflow: scroll">
            <div v-for="item in state.items" v-bind:key="item.id">
                <CartContenttItem v-bind="item" />
            </div>
        </div>
        <h2 v-if="state.items.length === 0">Empty Cart :(</h2>
    </div>
    <Divider />
    <div id="total-price-container">
        <h3>Total Price</h3>
        <h3>{{ state.totalPrice }}</h3>
    </div>
</template>

<script lang="ts">
import { defineComponent, inject } from "vue";
import { CartBloc } from "@frontend-clean-architecture/core";
import { useBlocState } from "../common/use-bloc-state";
import CartContenttItem from "./CartContenttItem.vue";

export default defineComponent({
    components: {
        CartContenttItem,
    },
    setup() {
        const bloc = inject<CartBloc>("cartBloc") as CartBloc;
        const state = useBlocState(bloc);

        return { state };
    },
});
</script>

<style scoped>
#info-container {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
}
#items-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    min-height: 150px;
    justify-content: space-around;
}
#total-price-container {
    display: flex;
    align-items: center;
    padding: 8px 0px;
    justify-content: space-around;
}
</style>

// packages/react-app/src/cart/cart-content.tsx
import React from 'react';
import { makeStyles, Theme } from '@material-ui/core/styles';
import { List, Divider, Box, Typography, CircularProgress } from '@material-ui/core';
import CartContentItem from './cart-content-item';
import { CartItemState } from '@frontend-clean-architecture/core';
import { useCartBloc } from '../app/app';
import { useBlocState } from '../common/use-bloc-state';

const useStyles = makeStyles((theme: Theme) => ({
  totalPriceContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: theme.spacing(1, 0),
    justifyContent: 'space-around',
  },
  itemsContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: theme.spacing(1, 0),
    justifyContent: 'space-around',
    minHeight: 150,
  },
  itemsList: {
    overflow: 'scroll',
  },
  infoContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100vh',
  },
}));

const CartContent: React.FC = () => {
  const classes = useStyles();
  const bloc = useCartBloc();
  const state = useBlocState(bloc);

  const cartItems = (items: CartItemState[]) => (
    <List className={classes.itemsList}>
      {items.map((item, index) => (
        <CartContentItem key={index} cartItem={item} />
      ))}
    </List>
  );

  const emptyCartItems = () => (
    <React.Fragment>
      <Typography variant="h6" component="h2">
        Empty Cart :(
      </Typography>
    </React.Fragment>
  );

  switch (state.kind) {
    case 'LoadingCartState': {
      return (
        <div className={classes.infoContainer}>
          <CircularProgress />
        </div>
      );
    }
    case 'ErrorCartState': {
      return (
        <div className={classes.infoContainer}>
          <Typography display="inline" variant="h5" component="h2">
            {state.error}
          </Typography>
        </div>
      );
    }
    case 'UpdatedCartState': {
      return (
        <React.Fragment>
          <Box flexDirection="column" className={classes.itemsContainer}>
            {state.items.length > 0 ? cartItems(state.items) : emptyCartItems()}
          </Box>
          <Divider />
          <Box flexDirection="row" className={classes.totalPriceContainer}>
            <Typography variant="h6" component="h2">
              Total Price
            </Typography>
            <Typography variant="h6" component="h2">
              {state.totalPrice}
            </Typography>
          </Box>
        </React.Fragment>
      );
    }
  }
};

export default CartContent;
