// packages/vue-app/src/app.vue
<template>
  <div id="app">
    <MyAppBar />
    <ProductList searchTerm="Element" />
    <CartSidebar />
  </div>
</template>

<script lang="ts">
import { dependenciesLocator } from '@frontend-clean-architecture/core';
import { defineComponent } from 'vue';
import MyAppBar from './appbar/MyAppBar.vue';
import ProductList from './products/ProductList.vue';
import CartSidebar from './cart/CartSidebar.vue';

export default defineComponent({
  name: 'App',
  components: {
    ProductList,
    MyAppBar,
    CartSidebar,
  },
  provide: {
    cartBloc: dependenciesLocator.provideCartBloc(),
  },
});
</script>

// packages/react-app/src/app/app.tsx
import React from 'react';
import MyAppBar from '../appbar/my-appbar';
import { CartBloc, dependenciesLocator } from '@frontend-clean-architecture/core';
import { createContext } from '../common/context';
import ProductList from '../products/product-list';
import CartDrawer from '../cart/cart-drawer';

const [blocContext, useBloc] = createContext<CartBloc>();

export const useCartBloc = useBloc;

const App: React.FC = () => {
  return (
    <blocContext.Provider value={dependenciesLocator.provideCartBloc()}>
      <MyAppBar />
      <ProductList />
      <CartDrawer />
    </blocContext.Provider>
  );
};

export default App;
