// packages/react-app/src/appbar/my-appbar.tsx
import { makeStyles } from '@material-ui/core/styles';
import AppBar from '@material-ui/core/AppBar';
import Toolbar from '@material-ui/core/Toolbar';
import IconButton from '@material-ui/core/IconButton';
import Badge from '@material-ui/core/Badge';
import ShoppingCartIcon from '@material-ui/icons/ShoppingCart';
import logo from './logo.png';
import reactLogo from './react-logo.png';
import { useCartBloc } from '../app/app';
import { useBlocState } from '../common/use-bloc-state';

const useStyles = makeStyles(() => ({
  toolbar: {
    justifyContent: 'space-between',
    maxWidth: '800',
  },
}));

const MyAppBar: React.FC = () => {
  const classes = useStyles();
  const bloc = useCartBloc();
  const state = useBlocState(bloc);

  const totalItems = state.kind === 'UpdatedCartState' ? state.totalItems : 0;

  return (
    <AppBar position="static">
      <Toolbar className={classes.toolbar}>
        <div>
          <img src={logo} width={150} alt="logo" />
          <img src={reactLogo} width={40} alt="react logo" />
        </div>

        <IconButton color="inherit">
          <Badge badgeContent={totalItems} color="secondary">
            <ShoppingCartIcon onClick={() => bloc.openCart()} />
          </Badge>
        </IconButton>
      </Toolbar>
    </AppBar>
  );
};

export default MyAppBar;

// packages/vue-app/src/appbar/my-appbar.vue
<template>
    <div>
        <Toolbar>
            <template #left>
                <img alt="logo" width="150" src="../assets/logo.png" />
                <img alt="Vue logo" height="40" src="../assets/vue-logo.png" />
            </template>

            <template #right>
                <Button
                    icon="pi pi-shopping-cart"
                    label="Cart"
                    v-bind:badge="state.totalItems ? state.totalItems.toString() : '0'"
                    badgeClass="p-badge-danger"
                    @click="handleOpenCart"
                />
            </template>
        </Toolbar>
    </div>
</template>

<script lang="ts">
import { defineComponent, inject } from "vue";
import { CartBloc } from "@frontend-clean-architecture/core";
import { useBlocState } from "../common/use-bloc-state";

export default defineComponent({
    setup() {
        const cartBloc = inject<CartBloc>("cartBloc") as CartBloc;
        const state = useBlocState(cartBloc);

        const handleOpenCart = () => {
            cartBloc?.openCart();
        };

        return {
            state,
            handleOpenCart,
        };
    },
});
</script>

<style scoped>
.p-button .p-badge {
    margin-right: 0.5rem;
}
</style>
